### ISSUE TITLE
New BXA release

### ISSUE THREAD

**Issue by JohannesBuchner** [JohannesBuchner/BXA#14]
I just released a new version (3.4.0) @alexkolo @ruizca @anetasie @bwgref @cdeil. Please test it if you can.

**Comment by JohannesBuchner** [comment]
This primarily improves the PCA-based background models (auto_background
function) to work better for XMM. There are a few more bug fixes.

The xz_auto.py and xz_auto_multiple.py scripts in examples/sherpa/ are
useful for automatically fitting one or more spectra of obscured AGN.
Here you can give the spectral files (e.g. FILENAME=src.pi ELO=0.5
EHI=8) and a src.pi.z file (containing the redshift) a src.pi.nh file
(containing the galactic NH value), and it will proceed to spit out
posterior chains of absorption, intrinsic and absorbed flux, photon
index, scattered powerlaw fraction, etc.

There is also a way to avoid installation of MultiNest now, by using
# in sherpa:
from bxa.sherpa.solver import BXASolver
solver = BXASolver(prior=priorfunction, parameters=parameters,
outputfiles_basename=outputfiles_basename)
solver.run()
# in xspec:
from bxa.xspec.solver import BXASolver
solver = BXASolver(transformations=transformations,
outputfiles_basename=outputfiles_basename)
solver.run()

and setting the environment variable WITHOUT_MULTINEST=1. This is not
yet documented, but do let me know if it works for you.

If you encounter issues, please open an issue.

**Comment by alexkolo** [comment]
Thanks for the update. 

So, the `BXASolver` is based on UltraNest?

My current project used the previous version of BXA and I didn't run into any problems. Should I redo my fits with this version because of some previous inaccuracies?

For future projects, I was actually wondering if it wouldn't be more consisting of using `UltraNest` directly instead of using the additional "layer" of `BXA`, since I would also use it also for non-`XSPEC` fits. Would that be advisable?

**Comment by JohannesBuchner** [comment]
UltraNest is a general-purpose fitting package. There are tutorials available here: https://johannesbuchner.github.io/UltraNest/ . You only need BXA for X-ray spectral fitting, as an interface to xspec or sherpa.

No need to redo any fits, there were no severe bugs, only error messages that occur in some software environments.
