### ISSUE TITLE
JOSS review: CI and testing  

### ISSUE THREAD

**Issue by grburgess** [JohannesBuchner/BXA#21]
Is there a link to the CI tests that can be included in README showing which software platforms BXA currently runs on (eg. linux/macos) as well the python versions?

These could be useful for building examples that work out-of-the-box as well as informing the users of pitfalls in installing the software.

**Comment by grburgess** [comment]
linking https://github.com/openjournals/joss-reviews/issues/3045

**Comment by JohannesBuchner** [comment]
BXA does not contain any platform-dependent code, so it is only a matter of whether xspec/sherpa runs on that platform.

CI capabilities are very limited, because installation takes over 1 hour.

BXA does not have any strong python version requirements, python 2.7 is still supported, as are early 3 versions. If not, it is a bug. However, these days it is difficult to create a python 2.7 environment with the dependencies (e.g., astropy).

**Comment by JohannesBuchner** [comment]
I think this was answered, if not, please reopen.
